{% set version = "0.16.0rc0" %}

package:
  name: iris-grib
  version: {{ version }}

source:
  url: https://github.com/SciTools/iris-grib/archive/v{{ version }}.tar.gz
  sha256: fe9a4fcecbf4b9f6d24b224c4ca58c5065ac2640929104fbac17e4045391fd5f

build:
  number: 0
  skip: true  # [win or py<36]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python>=3
    - iris>=3.0.0rc0
    - python-eccodes

test:
  imports:
    - iris_grib

about:
  home: https://iris-grib.readthedocs.io
  license: LGPL-3.0
  license_family: LGPL
  license_file: COPYING.LESSER
  summary: Iris GRIB interface

extra:
  recipe-maintainers:
    - bjlittle
    - corinnebosley
    - lbdreyer
    - ocefpaf
    - pp-mo
