{% set version = "0.17.1" %}

package:
  name: iris-grib
  version: {{ version }}

source:
  url: https://github.com/SciTools/iris-grib/archive/v{{ version }}.tar.gz
  sha256: 8c0dd4ced2eea634fe2f1483f9f631c87d53285b6db8fd6615b488acf14c11f5

build:
  number: 0
  skip: true  # [win or py<37]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - iris >=3.0.2
    - python-eccodes
    - eccodes >=2.16

test:
  imports:
    - iris_grib

about:
  home: https://iris-grib.readthedocs.io
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: COPYING.LESSER
  summary: Iris GRIB interface

extra:
  recipe-maintainers:
    - bjlittle
    - corinnebosley
    - lbdreyer
    - ocefpaf
    - pp-mo
    - trexfeathers
