{% set version = "0.20.0" %}


package:
  name: iris-grib
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/iris_grib/iris_grib-{{ version }}.tar.gz
  sha256: 76da5d2932c84f7c62db00b25b2aba875d4fdc9a5e5658d26a90aebd72ed94d2

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools >=64
    - setuptools-scm >=8
  run:
    - python >=3.10
    - iris >=3.0.2
    - python-eccodes >=1.6.1
    - eccodes >=2.33

test:
  imports:
    - iris_grib
  # cannot run pip check b/c python-eccodes is named eccodes-python on PyPI :-/
  # commands:
  #   - pip check
  # requires:
  #   - pip

about:
  home: https://github.com/SciTools/iris-grib
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Iris GRIB interface
  doc_url: https://iris-grib.readthedocs.io
  dev_url: https://github.com/SciTools/iris-grib

extra:
  recipe-maintainers:
    - bjlittle
    - lbdreyer
    - ocefpaf
    - pp-mo
    - trexfeathers
