{% set version = "0.13.0" %}

package:
  name: iris-grib
  version: {{ version }}

source:
  url: https://github.com/SciTools/iris-grib/archive/v{{ version }}.tar.gz
  sha256: b25d43e30347ef702cdd6bfc62a4436e286ec3b7911b69aad93d25edba40a75e

build:
  number: 0
  skip: True  # [win or py3k]
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - iris >=2
    - python-eccodes

test:
  imports:
    - iris_grib
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://iris-grib.readthedocs.io
  license: LGPL-3.0
  license_family: LGPL
  license_file: COPYING.LESSER
  summary: 'Iris GRIB interface.'

extra:
  recipe-maintainers:
    - ocefpaf
    - bjlittle
    - djkirkham
    - pp-mo
    - corinnebosley
