{% set version = "0.13.0" %}

package:
  name: iris-grib
  version: {{ version }}

source:
  url: https://github.com/SciTools/iris-grib/archive/v{{ version }}.tar.gz
  sha256: 051fb31336170692c6a4cb47334315ec7fba8be92316e208183ab157739c0855

build:
  number: 1001
  skip: True  # [win or py3k]
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - iris >=2
    - python-eccodes

test:
  imports:
    - iris_grib

about:
  home: https://iris-grib.readthedocs.io
  license: LGPL-3.0
  license_family: LGPL
  license_file: COPYING.LESSER
  summary: 'Iris GRIB interface'

extra:
  recipe-maintainers:
    - corinnebosley
