{% set version = "0.12.0" %}

package:
  name: iris-grib
  version: {{ version }}

source:
  url: https://github.com/SciTools/iris-grib/archive/v{{ version }}.tar.gz
  sha256: c2e92d25d8bfd2ddff22ae47c4532c884678bac6ea0d935367eced051ae08bb3

build:
  number: 0
  skip: True  # [win or py3k]
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - python-ecmwf_grib
  run:
    - python
    - python-ecmwf_grib

test:
  requires:
    - iris
    - iris-sample-data
    - pep8
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://scitools.org.uk/iris-grib
  license: LGPL-3.0
  license_file: COPYING.LESSER
  summary: 'Iris GRIB interface.'

extra:
  recipe-maintainers:
    - ocefpaf
    - bjlittle
    - djkirkham
