{% set python_min = "3.12" %}
{% set version = "0.22.0" %}


package:
  name: iris-grib
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/i/iris_grib/iris_grib-{{ version }}.tar.gz
  sha256: e2bd30471c369d0a6adb08e66e92e2ba8c04fa5ac55779db8579b5b4390df616

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=77.0.3
    - setuptools-scm >=8
  run:
    - python >={{ python_min }}
    - iris >=3.10
    - python-eccodes >=1.6.1
    - eccodes >=2.33

test:
  imports:
    - iris_grib
  requires:
    - python {{ python_min }}

about:
  home: https://github.com/SciTools/iris-grib
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Iris GRIB interface
  doc_url: https://iris-grib.readthedocs.io
  dev_url: https://github.com/SciTools/iris-grib

extra:
  recipe-maintainers:
    - bjlittle
    - lbdreyer
    - ocefpaf
    - pp-mo
    - trexfeathers
