{% set version = "0.14.1" %}

package:
  name: iris-grib
  version: {{ version }}

source:
  url: https://github.com/SciTools/iris-grib/archive/v{{ version }}.tar.gz
  sha256: a8c0241c1052bbfbf9064d51d23c7478ef48977e075fde0e2cd413666e4290eb

build:
  number: 0
  skip: True  # [win]
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - iris >=2
    - python-eccodes

test:
  imports:
    - iris_grib

about:
  home: https://iris-grib.readthedocs.io
  license: LGPL-3.0
  license_family: LGPL
  license_file: COPYING.LESSER
  summary: 'Iris GRIB interface'

extra:
  recipe-maintainers:
    - corinnebosley
    - ocefpaf
