{% set python_min = "3.10" %}
{% set version = "0.21.0" %}


package:
  name: iris-grib
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/i/iris_grib/iris_grib-{{ version }}.tar.gz
  sha256: 3db8525848dbf3ea32052e68da2132ed21887bb119728e16ea2595cd05bc1035

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=64
    - setuptools-scm >=8
  run:
    - python >={{ python_min }}
    - iris >=3.0.2
    - python-eccodes >=1.6.1
    - eccodes >=2.33

test:
  imports:
    - iris_grib
  requires:
    - python {{ python_min }}

about:
  home: https://github.com/SciTools/iris-grib
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Iris GRIB interface
  doc_url: https://iris-grib.readthedocs.io
  dev_url: https://github.com/SciTools/iris-grib

extra:
  recipe-maintainers:
    - bjlittle
    - lbdreyer
    - ocefpaf
    - pp-mo
    - trexfeathers
