{% set name = "iris-grib" %}
{% set version = "0.18.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/SciTools/iris-grib/archive/v{{ version }}.tar.gz
  sha256: e41b652caee899c92b2b7d0c9beeb074c4e82042df88c9d6d937278f5702f624

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - iris >=3.0.2
    - python-eccodes
    - eccodes >=2.16

test:
  imports:
    - iris_grib
  # cannot run pip check b/c python-eccodes is named eccodes-python on PyPI :-/
  # commands:
  #   - pip check
  # requires:
  #   - pip

about:
  home: https://iris-grib.readthedocs.io
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: COPYING.LESSER
  summary: Iris GRIB interface

extra:
  recipe-maintainers:
    - bjlittle
    - corinnebosley
    - lbdreyer
    - ocefpaf
    - pp-mo
    - trexfeathers
