{% set version = "0.17.0" %}

package:
  name: iris-grib
  version: {{ version }}

source:
  url: https://github.com/SciTools/iris-grib/archive/v{{ version }}.tar.gz
  sha256: 9fc00737e3eee770dfd2f969df55e6eeb13555980876946b753b4fa0874389cb

build:
  number: 0
  skip: true  # [win or py<36]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - iris >=3
    - python-eccodes
    - eccodes >=2.16

test:
  imports:
    - iris_grib

about:
  home: https://iris-grib.readthedocs.io
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: COPYING.LESSER
  summary: Iris GRIB interface

extra:
  recipe-maintainers:
    - bjlittle
    - corinnebosley
    - lbdreyer
    - ocefpaf
    - pp-mo
