{% set version = "0.14.0" %}

package:
  name: iris-grib
  version: {{ version }}

source:
  url: https://github.com/SciTools/iris-grib/archive/v{{ version }}.tar.gz
  sha256: 5e60eb54ff1bffe0791d0854870907bbc43717efbeb18ead4ce1555cab2b9fd6

build:
  number: 0
  skip: True  # [win or py3k]
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - iris >=2
    - python-eccodes

test:
  imports:
    - iris_grib

about:
  home: https://iris-grib.readthedocs.io
  license: LGPL-3.0
  license_family: LGPL
  license_file: COPYING.LESSER
  summary: 'Iris GRIB interface'

extra:
  recipe-maintainers:
    - corinnebosley
