provider:
  win: azure
conda_forge_output_validation: true

channels:
  sources:
    - conda-forge
    - defaults
    - conda-forge/label/rc_iris
  targets:
    - ["conda-forge", "rc_iris_grib"]

numpy:
  - 1.18