appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: fqi+9TJKDEC0vjfTmsi2NoLKyxwXvdJHfB3SbRUcenDjtnYCFQnPy4i/By7YkamnBq95JtrpD8spHXbV4WlN7xgiB073Ygz241kdZ/B5B7OZ+RqXqA5JOhUH7p81deTI54C2L0KIxf/+ch3KT7jpb+L0fomn7IiHNdv6gIXal+FgDMmWchLk8B3yeat6jzR//lP9Ro99Dt3uIv3NaIBT02myb7aTy3xJhcmdh0d/jZOqCATvY/T7hn2mCjfr+MRK9vVAbgh02SQxBlEv551LqrWKAzf1dXWULu0f9Onv2/E5vOSwckAdssPSLmxD9pnCJyrVNP0RAX8isTupikcorUpJuf3yyfxXQjbdKubtVD/5fgCI2nY15WUt7VGDthGSqQ0W+SXR85B8uz4qcys1F+2B4sXLpC6c9SLjnuU5FucEneTIDosCTTKlox/z9PgMZxyYR25hccO/DuZGXeqydSFaO5Smzecwgjr8p1jhtLIHeDyGe6yvg8THPYiVMk4pEOkeYLsEW+besSoJD9jLsmJkFcrRRIqI2ez9cwDhdT+djRVsK3vEWzcjftDEaMW24YeGxWchaDDQREV1shMmXcF6AN35MyFXV4tuC/DkgyAxjOdg+4ZR49w4RSe9NNxYofIRsVDpD4QSPuaUlSMuqY/CR2UlJzYGVqlydjoFrqI=}
provider:
  win: azure
conda_forge_output_validation: true
