travis:
  secure:
    BINSTAR_TOKEN: rETxsrkbUAt04Z+4+VhUcR4gPPDMPhpBXDTP2dXxp/qzzOTOxMbh2cvi1LvIANPD0OsBkW580SjSXPUlWrayBEgNeogNhRiwwF6Ht/C2FvxUV6IHXRGFVsJaeJ+uFkHCW+fCpcYKjUfddmZsYvIZftr+NH+4lDFHnmIXiM3bHVsjPwTV/A/VSNVPi4Ca/2zQvRRPtiLkuQ0RwRjLRNpAX8A5Ev+3Q2wFiM8V6FyKYLJ4bjvuvUZSwix93aiCs3SW1Kg2EmzrfqBq+NBMWuf2n4uuocSzZvSnb/iqn+ubSIqLDGaT9+nVZZ/HXOQLv1hQgTWs6WGJo3X2e+kqL/gbD+NEbcm9yq+DBScE7z3QxmwoiAWE0HGBbYKxqeQ6Y/ImnCwC/TAyPnX3J2CRaq/3cwahviL975j289d+dHPW5v+iTSGRTGLQWutwfzIDXrU6Ol9XX5+2qdfMs5OnF3kj1VIuGWjf2ybWFBpX4p565oeLTFSPlM5UWTuxxVIH8KnoUD2CyYf+WdvzHwzgKERjdjReGxaxDh3c6/6lqqRL5/84XM1rS6I2Hry1PlmV1g2dFaLe0ma5jf08HTnZrUL1AmiWAZOX5LIagTHnFSEvTbl5TZuQSaOHePDMqVaT0+yAFi8rYn1R2Wa2J0HfCGf+8FLAqroJJ6eM+IDGMd0iIug=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
